/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConvitesRouteImport } from './routes/convites'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdososIndexRouteImport } from './routes/idosos.index'
import { Route as IdososIdRouteImport } from './routes/idosos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvitesRoute = ConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdososIndexRoute = IdososIndexRouteImport.update({
  id: '/idosos/',
  path: '/idosos/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdososIdRoute = IdososIdRouteImport.update({
  id: '/idosos/$id',
  path: '/idosos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/convites': typeof ConvitesRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/idosos/$id': typeof IdososIdRoute
  '/idosos/': typeof IdososIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/convites': typeof ConvitesRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/idosos/$id': typeof IdososIdRoute
  '/idosos': typeof IdososIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/convites': typeof ConvitesRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/idosos/$id': typeof IdososIdRoute
  '/idosos/': typeof IdososIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/convites'
    | '/historico'
    | '/login'
    | '/idosos/$id'
    | '/idosos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/convites'
    | '/historico'
    | '/login'
    | '/idosos/$id'
    | '/idosos'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/convites'
    | '/historico'
    | '/login'
    | '/idosos/$id'
    | '/idosos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ConvitesRoute: typeof ConvitesRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  IdososIdRoute: typeof IdososIdRoute
  IdososIndexRoute: typeof IdososIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convites': {
      id: '/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof ConvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idosos/': {
      id: '/idosos/'
      path: '/idosos'
      fullPath: '/idosos/'
      preLoaderRoute: typeof IdososIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idosos/$id': {
      id: '/idosos/$id'
      path: '/idosos/$id'
      fullPath: '/idosos/$id'
      preLoaderRoute: typeof IdososIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ConvitesRoute: ConvitesRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  IdososIdRoute: IdososIdRoute,
  IdososIndexRoute: IdososIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
