/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuidadoresRouteImport } from './routes/cuidadores'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as IdososIndexRouteImport } from './routes/idosos.index'
import { Route as IdososIdRouteImport } from './routes/idosos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadoresRoute = CuidadoresRouteImport.update({
  id: '/cuidadores',
  path: '/cuidadores',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const IdososIndexRoute = IdososIndexRouteImport.update({
  id: '/idosos/',
  path: '/idosos/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdososIdRoute = IdososIdRouteImport.update({
  id: '/idosos/$id',
  path: '/idosos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuidadores': typeof CuidadoresRoute
  '/historico': typeof HistoricoRoute
  '/idosos/$id': typeof IdososIdRoute
  '/idosos/': typeof IdososIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuidadores': typeof CuidadoresRoute
  '/historico': typeof HistoricoRoute
  '/idosos/$id': typeof IdososIdRoute
  '/idosos': typeof IdososIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuidadores': typeof CuidadoresRoute
  '/historico': typeof HistoricoRoute
  '/idosos/$id': typeof IdososIdRoute
  '/idosos/': typeof IdososIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuidadores' | '/historico' | '/idosos/$id' | '/idosos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuidadores' | '/historico' | '/idosos/$id' | '/idosos'
  id:
    '__root__' | '/' | '/cuidadores' | '/historico' | '/idosos/$id' | '/idosos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuidadoresRoute: typeof CuidadoresRoute
  HistoricoRoute: typeof HistoricoRoute
  IdososIdRoute: typeof IdososIdRoute
  IdososIndexRoute: typeof IdososIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidadores': {
      id: '/cuidadores'
      path: '/cuidadores'
      fullPath: '/cuidadores'
      preLoaderRoute: typeof CuidadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idosos/': {
      id: '/idosos/'
      path: '/idosos'
      fullPath: '/idosos/'
      preLoaderRoute: typeof IdososIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idosos/$id': {
      id: '/idosos/$id'
      path: '/idosos/$id'
      fullPath: '/idosos/$id'
      preLoaderRoute: typeof IdososIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuidadoresRoute: CuidadoresRoute,
  HistoricoRoute: HistoricoRoute,
  IdososIdRoute: IdososIdRoute,
  IdososIndexRoute: IdososIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
