"""create historico_vinculo table

Revision ID: 1bb221513a35
Revises: fca2d4f050ff
Create Date: 2026-08-15 11:56:06.513491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb221513a35'
down_revision: Union[str, Sequence[str], None] = 'fca2d4f050ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.Enum('SAIU', 'REMOVIDO', name='tipo_evento_vinculo'), nullable=False),
    sa.Column('realizado_por_cuidador_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.ForeignKeyConstraint(['realizado_por_cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_vinculo')
    # ### end Alembic commands ###
