"""idoso idade para data_nascimento, validacao telefone

Revision ID: 3350335ecce2
Revises: 57c204bc42db
Create Date: 2026-08-15 00:48:09.902086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3350335ecce2'
down_revision: Union[str, Sequence[str], None] = '57c204bc42db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idosos', sa.Column('data_nascimento', sa.Date(), nullable=False))
    op.drop_column('idosos', 'idade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idosos', sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('idosos', 'data_nascimento')
    # ### end Alembic commands ###
