"""create idosos cuidadores tables

Revision ID: 57c204bc42db
Revises: 
Create Date: 2026-08-15 00:21:44.216682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c204bc42db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por_cuidador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idosos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por_cuidador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idoso_cuidador',
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('vinculado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('vinculado_por_cuidador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.ForeignKeyConstraint(['vinculado_por_cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('idoso_id', 'cuidador_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idoso_cuidador')
    op.drop_table('idosos')
    op.drop_table('cuidadores')
    # ### end Alembic commands ###
