"""create medicamentos table

Revision ID: e09521b3d190
Revises: 3350335ecce2
Create Date: 2026-08-15 01:40:58.853546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09521b3d190'
down_revision: Union[str, Sequence[str], None] = '3350335ecce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interacoes_medicamentosas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principio_ativo_a', sa.String(), nullable=False),
    sa.Column('principio_ativo_b', sa.String(), nullable=False),
    sa.Column('nivel_risco', sa.Enum('baixo', 'moderado', 'alto', name='nivel_risco'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_medicamentosas_principio_ativo_a'), 'interacoes_medicamentosas', ['principio_ativo_a'], unique=False)
    op.create_index(op.f('ix_interacoes_medicamentosas_principio_ativo_b'), 'interacoes_medicamentosas', ['principio_ativo_b'], unique=False)
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('principio_ativo', sa.String(), nullable=False),
    sa.Column('dosagem', sa.String(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('frequencia_horas', sa.Integer(), nullable=False),
    sa.Column('registro_ms', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por_cuidador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_principio_ativo'), 'medicamentos', ['principio_ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicamentos_principio_ativo'), table_name='medicamentos')
    op.drop_table('medicamentos')
    op.drop_index(op.f('ix_interacoes_medicamentosas_principio_ativo_b'), table_name='interacoes_medicamentosas')
    op.drop_index(op.f('ix_interacoes_medicamentosas_principio_ativo_a'), table_name='interacoes_medicamentosas')
    op.drop_table('interacoes_medicamentosas')
    # ### end Alembic commands ###
