"""create registros_dose table

Revision ID: fa7d9d632772
Revises: e09521b3d190
Create Date: 2026-08-15 02:22:32.448098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7d9d632772'
down_revision: Union[str, Sequence[str], None] = 'e09521b3d190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_dose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('horario_previsto', sa.DateTime(), nullable=False),
    sa.Column('confirmado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicamento_id', 'horario_previsto', name='uq_registro_dose_medicamento_horario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_dose')
    # ### end Alembic commands ###
