"""create convites_vinculo table

Revision ID: fca2d4f050ff
Revises: afcd88a6d6f7
Create Date: 2026-08-15 04:22:15.097425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca2d4f050ff'
down_revision: Union[str, Sequence[str], None] = 'afcd88a6d6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convites_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_convidado_id', sa.Integer(), nullable=False),
    sa.Column('solicitado_por_cuidador_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ACEITO', 'RECUSADO', name='status_convite'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_convidado_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convites_vinculo')
    # ### end Alembic commands ###
